import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/navbar"
import Output from "@/components/output"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100 p-2`}>
        <div className="mx-auto min-h-screen max-w-prose space-y-4 rounded-md border border-gray-300 bg-gray-50 p-4">
          <Navbar />
          <Output />
          {children}
        </div>
      </body>
    </html>
  )
}
